spring:
  profiles:
    active: ${APP_PROFILE:json}
  main:
    banner-mode: off

server:
  port: 8080

carrent:
  json:
    users-file: src/main/resources/users.json
    vehicles-file: src/main/resources/vehicles.json
    rentals-file: src/main/resources/rentals.json
    categories-file: src/main/resources/categories.json